// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 4.7
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_basic(c,a,b){this.go=function(d){b.find("ul").stop(true).animate({left:(d?-d+"00%":(/Safari/.test(navigator.userAgent)?"0%":0))},c.duration,"easeInOutExpo");return d}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 4.7
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container2").wowSlider({effect:"basic",prev:"",next:"",duration:20*100,delay:89*80,width:960,height:360,autoPlay:true,playPause:true,stopOnHover:true,loop:false,bullets:0,caption:true,captionEffect:"fade",controls:true,onBeforeStep:0,images:[
    {src:"./980x360_AAX_Portal_NUGEN.jpg",title:"", href:"https://shop.avid.com/ccrz__Products?cartID=&operation=quickSearch&searchText=NUGEN&isCSRFlow=true&portalUser=&store=", target:"_blank"},
    {src:"./980x360_AAX_Portal_AvidPlugIns.jpg",title:"", href:"https://shop.avid.com/ccrz__ProductDetails?viewState=DetailView&cartID=&sku=BF%20Classic%20Compressors%20Bundle&&store=shop",target:"_blank"},
    {src:"./980x360_AAX_Portal_FluxPlugIns.jpg",title:"",href:"https://shop.avid.com/ccrz__Products?cartID=&operation=quickSearch&searchText=flux&isCSRFlow=true&portalUser=&store=shop",target:"_blank"},
    {src:"./980x360_AAX_Portal_Sonnox.jpg",title:"",href:"https://shop.avid.com/ccrz__Products?cartID=&operation=quickSearch&searchText=sonnox&isCSRFlow=true&portalUser=&store=shop",target:"_blank"},
    {src:"./980x360_AAX_Portal_Air.jpg",title:"",href:"https://shop.avid.com/ccrz__Products?cartID=&operation=quickSearch&searchText=Air%20Music%20Technology&isCSRFlow=true&portalUser=&store=shop",target:"_blank"}
]});
